apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: portainer-helm
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: portainer
  project: default
  sources:
    - chart: portainer
      repoURL: https://portainer.github.io/k8s/
      targetRevision: 2.33.6
      helm:
        parameters:
          - name: service.type
            value: "LoadBalancer"
          - name: image.tag
            value: "lts"
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true