---
services:
  guacd:
    image: guacamole/guacd:1.6.0
    container_name: guacd
    volumes:
      - /opt/containers/guacamole/drive:/drive:rw
      - /opt/containers/guacamole/record:/record:rw
    networks:
      - guacamole
    restart: unless-stopped

  postgres:
    image: postgres:15.2-alpine
    container_name: guacamole-db
    environment:
      PGDATA: /var/lib/postgresql/data/guacamole
      POSTGRES_DB: guacamole
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: guacamole
    volumes:
      - /opt/containers/guacamole/init:/docker-entrypoint-initdb.d:z
      - /opt/containers/guacamole/data:/var/lib/postgresql/data:Z
    networks:
      - guacamole
    restart: unless-stopped

  guacamole:
    image: guacamole/guacamole:1.6.0
    container_name: guacamole
    environment:
      GUACD_HOSTNAME: guacd
      POSTGRESQL_DATABASE: guacamole
      POSTGRESQL_HOSTNAME: postgres
      POSTGRESQL_PASSWORD: ${POSTGRESQL_PASSWORD}
      POSTGRESQL_USERNAME: guacamole
      RECORDING_SEARCH_PATH: /record
    volumes:
      - /opt/containers/guacamole/record:/record:rw
    networks:
      - guacamole
      - proxy
    depends_on:
      - guacd
      - postgres
    restart: unless-stopped

networks:
  guacamole:
  proxy: 
    external: true

