apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: harbor
  namespace: harbor
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`harbor.local.dontddos.me`)
      kind: Rule
      services:
        - name: harbor-helm-portal
          port: 80