---
services:
  nginx:
    image: nginx:latest
    container_name: website
    volumes:
      - ./content:/usr/share/nginx/html:ro
    networks:
      - newt
    restart: unless-stopped

networks:
  newt:
    external: true