apiVersion: v1
kind: Service
metadata:
  name: adguard-home-dns
  namespace: adguard
spec:
  kind: LoadBalancer
  selector:
    app: adguard-home
  ports:
  - port: 53
    targetPort: 53
    protocol: "TCP"
    name: "dns-tcp"
  - port: 53
    targetPort: 53
    protocol: "UDP"
    name: "dns-udp"
---
apiVersion: v1
kind: Service
metadata:
  name: adguard-home-http
spec:
  selector:
    app: adguard-home
  ports:
  - port: 80
    targetPort: 80
    name: "http"
  - port: 3000
    targetPort: 3000
    name: "http-setup"
