name: librenms

services:
  db:
    image: mariadb:10
    container_name: librenms_db
    command:
      - "mysqld"
      - "--innodb-file-per-table=1"
      - "--lower-case-table-names=0"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
    volumes:
      - "./db:/var/lib/mysql"
    environment:
      - "TZ=${TZ}"
      - "MARIADB_RANDOM_ROOT_PASSWORD=yes"
      - "MYSQL_DATABASE=${MYSQL_DATABASE}"
      - "MYSQL_USER=${MYSQL_USER}"
      - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
    networks:
      - librenms
    restart: unless-stopped

  redis:
    image: redis:7.2-alpine
    container_name: librenms_redis
    environment:
      - "TZ=${TZ}"
    networks:
      - librenms
    restart: unless-stopped

  msmtpd:
    image: crazymax/msmtpd:latest
    container_name: librenms_msmtpd
    environment:
      - SMTP_HOST=mail.dontddos.me
      - SMTP_PORT=587
      - SMTP_TLS=on
      - SMTP_STARTTLS=on
      - SMTP_TLS_CHECKCERT=on
      - SMTP_AUTH=on
      - SMTP_USER=no-reply@dontddos.me
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - SMTP_FROM=no-reply@dontddos.me
    networks:
      - librenms
    restart: unless-stopped

  librenms:
    image: librenms/librenms:latest
    container_name: librenms
    hostname: librenms
    cap_add:
      - NET_ADMIN
      - NET_RAW
    depends_on:
      - db
      - redis
      - msmtpd
    volumes:
      - "./librenms:/data"
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - DB_HOST=db
      - DB_NAME=${MYSQL_DATABASE}
      - DB_USER=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - DB_TIMEOUT=60
      - MEMORY_LIMIT=256M
      - MAX_INPUT_VARS=1000
      - UPLOAD_MAX_SIZE=16M
      - OPCACHE_MEM_SIZE=128
      - REAL_IP_FROM=0.0.0.0/32
      - REAL_IP_HEADER=X-Forwarded-For
      - LOG_IP_VAR=remote_addr
      - CACHE_DRIVER=redis
      - SESSION_DRIVER=redis
      - REDIS_HOST=redis
      - LIBRENMS_SNMP_COMMUNITY=${LIBRENMS_SNMP_COMMUNITY}
      - LIBRENMS_WEATHERMAP=false
      - LIBRENMS_WEATHERMAP_SCHEDULE=*/5 * * * *
    networks:
      - librenms
      - proxy
    restart: unless-stopped

  dispatcher:
    image: librenms/librenms:latest
    container_name: librenms_dispatcher
    hostname: librenms-dispatcher
    cap_add:
      - NET_ADMIN
      - NET_RAW
    depends_on:
      - librenms
      - redis
    volumes:
      - "./librenms:/data"
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - DB_HOST=db
      - DB_NAME=${MYSQL_DATABASE}
      - DB_USER=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - DB_TIMEOUT=60
      - DISPATCHER_NODE_ID=dispatcher1
      - SIDECAR_DISPATCHER=1
      - MEMORY_LIMIT=256M
      - MAX_INPUT_VARS=1000
      - UPLOAD_MAX_SIZE=16M
      - OPCACHE_MEM_SIZE=128
      - REAL_IP_FROM=0.0.0.0/32
      - REAL_IP_HEADER=X-Forwarded-For
      - LOG_IP_VAR=remote_addr
      - CACHE_DRIVER=redis
      - SESSION_DRIVER=redis
      - REDIS_HOST=redis
      - LIBRENMS_SNMP_COMMUNITY=${LIBRENMS_SNMP_COMMUNITY}
      - LIBRENMS_WEATHERMAP=false
      - LIBRENMS_WEATHERMAP_SCHEDULE=*/5 * * * *
    networks:
      - librenms
    restart: unless-stopped

  syslogng:
    image: librenms/librenms:latest
    container_name: librenms_syslogng
    hostname: librenms-syslogng
    cap_add:
      - NET_ADMIN
      - NET_RAW
    depends_on:
      - librenms
      - redis
    ports:
      - target: 514
        published: 514
        protocol: tcp
      - target: 514
        published: 514
        protocol: udp
    volumes:
      - "./librenms:/data"
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - DB_HOST=db
      - DB_NAME=${MYSQL_DATABASE}
      - DB_USER=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - DB_TIMEOUT=60
      - SIDECAR_SYSLOGNG=1
      - MEMORY_LIMIT=256M
      - MAX_INPUT_VARS=1000
      - UPLOAD_MAX_SIZE=16M
      - OPCACHE_MEM_SIZE=128
      - REAL_IP_FROM=0.0.0.0/32
      - REAL_IP_HEADER=X-Forwarded-For
      - LOG_IP_VAR=remote_addr
      - CACHE_DRIVER=redis
      - SESSION_DRIVER=redis
      - REDIS_HOST=redis
      - LIBRENMS_SNMP_COMMUNITY=${LIBRENMS_SNMP_COMMUNITY}
      - LIBRENMS_WEATHERMAP=false
      - LIBRENMS_WEATHERMAP_SCHEDULE=*/5 * * * *
    networks:
      - librenms
    restart: unless-stopped

  snmptrapd:
    image: librenms/librenms:latest
    container_name: librenms_snmptrapd
    hostname: librenms-snmptrapd
    cap_add:
      - NET_ADMIN
      - NET_RAW
    depends_on:
      - librenms
      - redis
    ports:
      - target: 162
        published: 162
        protocol: tcp
      - target: 162
        published: 162
        protocol: udp
    volumes:
      - "./librenms:/data"
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - DB_HOST=db
      - DB_NAME=${MYSQL_DATABASE}
      - DB_USER=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - DB_TIMEOUT=60
      - SIDECAR_SNMPTRAPD=1
      - MEMORY_LIMIT=256M
      - MAX_INPUT_VARS=1000
      - UPLOAD_MAX_SIZE=16M
      - OPCACHE_MEM_SIZE=128
      - REAL_IP_FROM=0.0.0.0/32
      - REAL_IP_HEADER=X-Forwarded-For
      - LOG_IP_VAR=remote_addr
      - CACHE_DRIVER=redis
      - SESSION_DRIVER=redis
      - REDIS_HOST=redis
      - LIBRENMS_SNMP_COMMUNITY=${LIBRENMS_SNMP_COMMUNITY}
      - LIBRENMS_WEATHERMAP=false
      - LIBRENMS_WEATHERMAP_SCHEDULE=*/5 * * * *
    networks:
      - librenms
    restart: unless-stopped

networks:
  librenms:
  proxy:
    external: true