apiVersion: apps/v1
kind: Deployment
metadata:
  name: termix
  namespace: termix
spec:
  selector:
    matchLabels:
      app: termix
  template:
    metadata:
      labels:
        app: termix
    spec:
      securityContext:
        fsGroup: 1000
      containers:
      - name: termix
        image: ghcr.io/lukegus/termix:latest
        ports:
        - containerPort: 8080
        env:
          - name: PORT
            volume: "8080"
        volumeMounts:
        - name: termix-data
          mountPath: /app/data
      volumes:
      - name: termix-data
        persistentVolumeClaim:
          claimName: termix-data