---
services:
  gitea:
    image: docker.gitea.com/gitea:1.25.3
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=db:5432
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=${POSTGRES_PASSWORD}
    networks:
      - gitea
      - newt
    volumes:
      - /opt/containers/gitea/gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: docker.io/library/postgres:14
    container_name: gitea-db
    environment:
      - POSTGRES_USER=gitea
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=gitea
    networks:
      - gitea
    ports:
      - 5400:5432
    volumes:
      - /opt/containers/gitea/postgres:/var/lib/postgresql/data
    restart: unless-stopped

networks:
  gitea:
  newt:
    external: true
