---
services:
  nginx:
    image: nginx:latest
    container_name: dontddosme
    volumes:
      - /opt/containers/dontddos.me/content:/usr/share/nginx/html:ro
    networks:
      - newt
    restart: unless-stopped

networks:
  newt:
    external: true
