---
services:
  jellyseerr:
    image: ghcr.io/fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - TZ=Etc/UTC
    volumes:
      - /opt/containers/jellyseerr/config:/app/config
    networks:
      - newt
    restart: unless-stopped

networks:
  newt:
    external: true
