---
- name: Deploy SSH authorized_keys
  hosts: all
  become: yes
  become_method: sudo
  tasks:
    - name: Ensure .ssh directory exists
      ansible.builtin.file:
        path: "{{ '/root' if ansible_user == 'root' else '/home/' + ansible_user }}/.ssh"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: "0700"

    - name: Deploy authorized_keys
      ansible.builtin.copy:
        src: ../files/authorized_keys
        dest: "{{ '/root' if ansible_user == 'root' else '/home/' + ansible_user }}/.ssh/authorized_keys"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: "0600"
        backup: yes