apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: vikunja-dbc
  namespace: vikunja
spec:
  instances: 3
  monitoring:
    enablePodMonitor: true
  storage:
    size: 5Gi
    storageClass: longhorn-single
  affinity:
    enablePodAntiAffinity: true
    topologyKey: kubernetes.io/hostname
    podAntiAffinityType: required
  bootstrap:
    initdb:
      database: vikunja
      owner: vikunja