apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homarr-helm
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: homarr
  project: default
  sources:
    - chart: homarr
      repoURL: https://homarr-labs.github.io/charts
      targetRevision: 8.9.0
      helm: 
        values: |
          replicaCount: 3
          database:
            type: postgresql
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true