---
services:
  synapse:
    container_name: synapse
    image: docker.io/matrixdotorg/synapse:latest
    environment:
      - SYNAPSE_CONFIG_PATH=/data/homeserver.yaml
      - UID=991
      - GID=991
    volumes:
      - /opt/containers/synapse/data:/data
    depends_on:
      - db
    networks:
      - synapse
      - newt
    restart: unless-stopped

  db:
    image: docker.io/postgres:15-alpine
    container_name: synapse-db
    environment:
      - POSTGRES_USER=synapse
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=synapse
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    volumes:
      - /opt/containers/synapse/db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - synapse
    restart: unless-stopped

networks:
  synapse:
  newt:
    external: true
