apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: internal-wildcard-cert
  namespace: traefik
spec:
  secretName: internal-wildcard-cert
  dnsNames:
    - "*.internal.dontddos.me"
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer