apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: local-wildcard-cert
  namespace: traefik
spec:
  secretName: local-wildcard-cert
  dnsNames:
    - "*.local.dontddos.me"
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer