apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: semaphore-helm
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: semaphore
  project: default
  sources:
    - chart: semaphore
      repoURL: https://semaphoreui.github.io/charts
      targetRevision: 16.0.11
      helm:
        values: |
          replicaCount: 3
          database:
            type: postgres
            host: semaphore-dbc-rw
            port: 5432
            existingSecret: semaphore-dbc-app
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true