apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: semaphore
  namespace: semaphore
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`semaphore.local.dontddos.me`)
      kind: Rule
      services:
        - name: semaphore-helm
          port: 3000