---
services:
  panel:
    image: ghcr.io/pelican-dev/panel:latest
    container_name: pelican-panel
    restart: unless-stopped
    networks:
      - newt
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - data:/pelican-data
      - logs:/var/www/html/storage/logs
      - /opt/containers/pelican/Caddyfile:/etc/caddy/Caddyfile
    environment:
      XDG_DATA_HOME: /pelican-data
      APP_URL: "https://pelican.dontddos.me"
      ADMIN_EMAIL: "admin@dontddos.me"

volumes:
  data:
  logs:

networks:
  newt:
    external: true