apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: librenms
  namespace: monitoring
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`librenms.local.dontddos.me`)
      kind: Rule
      services:
        - name: librenms-helm
          port: 8000