apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: immich-helm
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: immich
  project: default
  sources:
    - chart: immich
      repoURL: https://github.com/immich-app/immich-charts
      targetRevision: 0.10.3
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true