apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: immich-helm
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: immich
  project: default
  sources:
    - chart: .
      repoURL: oci://ghcr.io/immich-app/immich-charts/immich
      targetRevision: 0.10.3
      helm:
        values: |
          controllers:
            main:
              containers:
                main:
                  env:
                    REDIS_HOSTNAME: '{{ printf "%s-valkey" .Release.Name }}'
                    IMMICH_MACHINE_LEARNING_URL: '{{ printf "http://%s-machine-learning:3003" .Release.Name }}'
                    DB_HOSTNAME: 'immich-dbc-rw'
                    DB_PORT: '5432'
                    DB_USERNAME: 'immich'
                    DB_DATABASE_NAME: immich
                  envFrom:
                    - secretRef:
                        name: immich-db-password
          immich:
            persistence:
              library:
                existingClaim: immich-libary
          valkey:
            enabled: true
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true