apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: librenms-helm
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: librenms
  project: default
  sources:
    - chart: librenms
      repoURL: https://www.librenms.org/helm-charts
      targetRevision: 7.2.0
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true